export const DASHBOARD = '/dashboard';
export const USERDASHBOARD = '/dashboard/:id';
export const LOGIN = '/';
export const SIGNUP = '/signup';
export const USER = '/user/:id';
export const NOT_FOUND ='/not-found';
export const CONTACTS = '/contacts';
export const CAMPAIGNS ='/campaigns';
export const CAMPAIGN ='/campaigns/:id';
export const TEMPLATES ='/templates';
export const CERTIFICATE = "/certificate"
export const MUSICEVENT = "/musicevent"
export const ENERGYBILL = "/energybill"